state_file = "auto"
engine = "whisper"

[audio]
device = "alsa_input.usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-00.analog-stereo"
sample_rate = 16000
max_duration_secs = 120

[hotkey]
enabled = false

[whisper]
model = "large-v3-turbo"
language = "en"
translate = false
on_demand_loading = false

[output]
mode = "type"
fallback_to_clipboard = true
pre_type_delay_ms = 150

[output.notification]
on_recording_start = true
on_recording_stop = true
on_transcription = true
